### PR TITLE
Adding Hover Effect

### PR DESCRIPTION
**Pull request by shwetazade27**
## Related Issue
#56

Added hovering effect and animation on cards of extra section

### CODE REVIEW

**Comment by kuvamdazeus** [comment]
Great work @shwetazade27 🙌🏻

There are 2 suggestions I have for it:
1. animation of background color on hover
2. make the cursor a pointer when hovering

Let me know if you can do these and I'll merge the PR 👍🏻

**Comment by shwetazade27** [comment]
Thankyou sir @kuvamdazeus 
Sure.. I would like to  try working on suggestions

**Comment by kuvamdazeus** [comment]
if you face any problem in implementing them, lemme know

**Comment by shwetazade27** [comment]
@kuvamdazeus sir please elaborate 1st suggestion....like where to add animation of color , background of cards or on card

**Comment by kuvamdazeus** [comment]
I want you add animation to the background of the cards,
you know when we hover, it grows big with nice animation & delay, but the background colour changes instantly,

I want you to animate the background colour change of the card.

Also, please call me by my name, "sir" seems too fancy 😅😂

**Comment by shwetazade27** [comment]
@kuvamdazeus okay got it .. will try to work on it.. Thankyou

**Comment by shwetazade27** [comment]
@kuvamdazeus I have made changes please let me know if further improvements or changes are required..

**Comment by kuvamdazeus** [comment]
Amazing job @shwetazade27, thanks for your contribution !!

**Comment by shwetazade27** [comment]
Thankyou @kuvamdazeus ..please let me know if I can contribute in any other issues as well.

**Comment by kuvamdazeus** [comment]
Actually @shwetazade27, here people are generally creating issues themselves,
why don't you look for any improvements that you can make to the website yourself?

Just like you found this one.

Moreover, I don't have any new issue ideas in my mind tbh 😅

**Comment by shwetazade27** [comment]
sure ..Thankyou @kuvamdazeus

**Pull request merged**
