### PR TITLE
Feat : Error Page Added

### PR DESCRIPTION
**Pull request by PatilHarshh**
Error page added 
issue no :  #116

### CODE REVIEW

**Comment by PatilHarshh** [comment]
@Spyware007 please merge it

**Comment by Bhushan8177** [comment]
Great work @PatilHarshh , I must say great design 🙌👏!!
Can we have something in place of that white background , may be it will enhance the page according to me !!

**Comment by PatilHarshh** [comment]
sure @Bhushan8177

**Comment by Grab-Bits** [comment]
Hey @PatilHarshh , any updates regarding the same ??

**Comment by PatilHarshh** [comment]
please @Grab-Bits and @Bhushan8177  Can you Check Now I Think This will Suites to Our Website....

**Comment by Grab-Bits** [comment]
> please @Grab-Bits and @Bhushan8177 Can you Check Now I Think This will Suites to Our Website....

Hey @PatilHarshh ,I think  Plain  colour won't fill the entire blank space, I guess you can go with some background patterns, gradients or anything that would look cool !!

**Comment by PatilHarshh** [comment]
@Grab-Bits now Can You Check , Tell me if Changes needed

**Comment by Grab-Bits** [comment]
Great work @PatilHarshh, Can we have something in place of that white background , may be it will enhance the page according to me !!

**Comment by PatilHarshh** [comment]
@Grab-Bits i added background there

**Comment by PatilHarshh** [comment]
> @Grab-Bits i added background there

Not visible ?

**Comment by PatilHarshh** [comment]
Screenshot (114)

**Comment by PatilHarshh** [comment]
@Grab-Bits

**Comment by PatilHarshh** [comment]
@Bhushan8177

**Comment by Bhushan8177** [comment]
I deployed your pr, but it was not visible @PatilHarshh

**Comment by Bhushan8177** [comment]
I will look into it!

**Comment by Bhushan8177** [comment]
Great work @PatilHarshh  , Merging this !!
Thank you for Contributing to GrabBit!!
Please ⭐ the repository and follow me on Github ...!

You can connect with me on Linkedin -
https://www.linkedin.com/in/bhushan-kale/

**Pull request merged**
