### PR TITLE
added tech stacks

### PR DESCRIPTION
**Pull request by mridulsaggi**
added the tech stack shields
image

### CODE REVIEW

**Comment by kuvamdazeus** [comment]
Hi @mridulsaggi 

Thanks for adding tech stack documentation,
But we'll be needing a little more detail on this one,

You see, this is a full-stack project as it has its frontend & backend,

While your suggestion for adding HTML, CSS & Javascript is technically correct, we have to be more specific on the prominent frameworks & libraries used alongside javascript in the backend & frontend.

Allow me to suggest you the tech stack in a way that it'll be clear to newcomers what exact technology we're using here.

Under the tech stack section, you might create 2 sub-sections:
- **Frontend** : React.js, HTML, CSS
- **Backend** : Node.js, Express.js, MongoDB

Let me know if you have any difficulty with this one, I'll help you out :)

**Comment by mridulsaggi** [comment]
yes sure i will make the required changes.

**Comment by mridulsaggi** [comment]
i have added the frontend and backend tech stacks . pls check

**Comment by kuvamdazeus** [comment]
I think you forgot "React.js" there in the frontend section,

Also, please do "Tech Stack used at ..." instead of "Tech Stacks used at ..." there,
"Stacks" needs to be a singular word.

**Comment by mridulsaggi** [comment]
updated the changes

**Pull request merged**
