### PR TITLE
handling tags dislocation

### PR DESCRIPTION
**Pull request by Shashank2104125**
## Related Issue

Closes: #[issue number]
#92

## Description of Changes
To handle this issue just make a parent div for search bar and add media query to it.

## Checklist:

- [x] My code adheres to the established style guidelines of this project.
- [x] I have conducted a self-review of my code.
- [x] I have included comments in areas that may be difficult to understand.
- [x] My changes have not introduced any new warnings.

## Screenshots/Video

https://github.com/GrabBits/GrabBits_Website/assets/97789487/e4ce879f-8cfa-4e4f-bd4b-6a1fc56c1efc

### CODE REVIEW

**Comment by Bhushan8177** [comment]
Hii @Shashank2104125 , can you elaborate a bit about how you are going to contribute for it !

**Comment by Shashank2104125** [comment]
> Hii @Shashank2104125 , can you elaborate a bit about how you are going to contribute for it !

@Bhushan8177 if you are asking about the process which I follow to resolve this issue so I am just using media query to tackle this issue.

**Comment by Grab-Bits** [comment]
No @Shashank2104125 , what changes have you brought up in the issue I want to know that !

**Comment by Shashank2104125** [comment]
> No @Shashank2104125 , what changes have you brought up in the issue I want to know that !

@Bhushan8177  this is the issue check it->https://github.com/GrabBits/GrabBits_Website/assets/97789487/8c6cb590-0991-4da3-a374-918c90fc672b

**Comment by Shashank2104125** [comment]
> > No @Shashank2104125 , what changes have you brought up in the issue I want to know that !
> 
> @Bhushan8177 this is the issue check it->https://github.com/GrabBits/GrabBits_Website/assets/97789487/8c6cb590-0991-4da3-a374-918c90fc672b
Tags slightly dislocate from their original position while pointing to search bar.

**Comment by kuvamdazeus** [comment]
Great work @Shashank2104125 !!

If you have noticed, the current behaviour of the search bar is not favourable with it returning to its original state and the text that you've written gets reset when the mouse pointer leaves the expanded div.

What do you think, how can we change that and give a more friendly experience to users?

If you're comfortable with this problem, we can discuss this here, if you come up with a solution, I can create another issue for this problem & then you can start working on that & I'll merge this PR.

**Comment by Shashank2104125** [comment]
> Great work @Shashank2104125 !!
> 
> If you have noticed, the current behaviour of the search bar is not favourable with it returning to its original state and the text that you've written gets reset when the mouse pointer leaves the expanded div.
> 
> What do you think, how can we change that and give a more friendly experience to users?
> 
> If you're comfortable with this problem, we can discuss this here, if you come up with a solution, I can create another issue for this problem & then you can start working on that & I'll merge this PR.
@kuvamdazeus Sure!! merge this PR and I am opening a new issue for this assign it to me.

**Comment by Shashank2104125** [comment]
> > Great work @Shashank2104125 !!
> > If you have noticed, the current behaviour of the search bar is not favourable with it returning to its original state and the text that you've written gets reset when the mouse pointer leaves the expanded div.
> > What do you think, how can we change that and give a more friendly experience to users?
> > If you're comfortable with this problem, we can discuss this here, if you come up with a solution, I can create another issue for this problem & then you can start working on that & I'll merge this PR.
> > @kuvamdazeus Sure!! merge this PR and I am opening a new issue for this assign it to me.

@kuvamdazeus now I am now open issure #106 for this. Please merge this one assign this issue to me.

**Pull request merged**
