### PR TITLE
Closes: #24

### PR DESCRIPTION
**Pull request by tuhinaww**
## Related Issue

Closes: #24 

## Description of Changes
- Created ".github" folder and added new templates under "issue_template" to report bugs and add new features.
- Created file under ".github" folder and added new template for PR.
- Creater "workflows" folder under ".github" that can send welcome messages to new contributors.

## Checklist:

- [x] My code adheres to the established style guidelines of this project.
- [x] I have conducted a self-review of my code.
- [x] I have included comments in areas that may be difficult to understand.
- [x] I have made corresponding updates to the project documentation.
- [x] My changes have not introduced any new warnings.

## Screenshots

|      Original       |       Updated        |
| :-----------------: | :------------------: |
|original | pull |
| original | feature |
| original | bugs |

## Additional Comments:
I will create a new issue to add "contributing.md" which will have all necessary steps to start contributing , "Code of Conduct" and other workflows. You can assign them to me.

### CODE REVIEW

**Comment by Bhushan8177** [comment]
hey @tuhinaww ,  can you create various md files for specific purposes, will be easier for the beginners to read and understand and update the readme accordingly

**Comment by tuhinaww** [comment]
Yes, Absolutely :)

**Comment by Bhushan8177** [comment]
Hey @tuhinaww , I am unable to see various files you created can you specify please

**Comment by tuhinaww** [comment]
## Yes so a new folder has been created called ".github"
image

In that 3 templates are being provided 
1. Bug Report
2. Feature Addition 
3. Pull Request

As mentioned above. After being merged, the new issue that will be created will get segregated between bug report and feature addition  
image
here are the files which are created by me under .github folder.

**Comment by Spyware007** [comment]
Thank you so much @tuhinaww 
Looking forward for more contributions from you. 🧑‍💻

**Pull request merged**
