### PR TITLE
email validation

### PR DESCRIPTION
**Pull request by Riyazul555**
## Related Issue

Closes: #[issue number]

## Checklist:

- [ ] My code adheres to the established style guidelines of this project.
- [ ] I have conducted a self-review of my code.
- [ ] I have included comments in areas that may be difficult to understand.
- [ ] I have made corresponding updates to the project documentation.
- [ ] My changes have not introduced any new warnings.

## Screenshots

|      Original       |       Updated        |
| :-----------------: | :------------------: |
| Original screenshot | Updated screenshot |

Please provide any necessary screenshots to illustrate the changes made.

### CODE REVIEW

**Comment by Riyazul555** [comment]
@Bhushan8177 I have made some changes in email validation ......please review it and let me know if you need any further changes

**Comment by Riyazul555** [comment]
@Bhushan8177 please review this pR

**Comment by Grab-Bits** [comment]
Hey @Riyazul555 , I deployed your pr . After deployment every page is getting blank and we have to refresh at every page !!
can you fix this ..!
Adding the ss - 
image

**Comment by Riyazul555** [comment]
I have to take a look .......give me some time @Grab-Bits

**Comment by Bhushan8177** [comment]
> I have to take a look .......give me some time @Grab-Bits 

Ok sure!

**Comment by Riyazul555** [comment]
Can you tell me why its showing error on npm installation  like which npm packages you are using 
and whats the command to run the server 

Screenshot (323)

**Comment by Grab-Bits** [comment]
Hey @Riyazul555 , I guess somebody is already working on the issue, Hence closing this, you can contribute to other issues and do let me know if you face any problems in the discord server !!

**Pull request closed without merging**
