### PR TITLE
FAQ section's css updated

### PR DESCRIPTION
**Pull request by Pragati-3003**
I have updated the css of the Frequently asked questions by adding some css effects.
Closes: #143
Please review and kindly inform me if you wanna  any other changes.

### CODE REVIEW

**Comment by Bhushan8177** [comment]
Hey @Pragati-3003 , I am unable to deploy your changes , will look into it, till then you can go for other issues !!

**Comment by Pragati-3003** [comment]
> Hey @Pragati-3003 , I am unable to deploy your changes , will look into it, till then you can go for other issues !!

okie

**Comment by Bhushan8177** [comment]
Hey @Pragati-3003 , there's still issue of the deployment !! 
I request you to please close this pr and create another one!!

**Comment by Pragati-3003** [comment]
> Hey @Pragati-3003 , there's still issue of the deployment !! I request you to please close this pr and create another one!!

Okie, will create another PR.

**Comment by Grab-Bits** [comment]
Hey @Pragati-3003 ,Sorry to say but I think the changes you made does not align with the theme of the project correctly , also the effects are a little too exhausting for a simple user experience !!
I request you to please observe the overall theme and UI of the project and then contribute towards better isssues, Thank you !!

**Pull request closed without merging**
