### PR TITLE
post a request to the API from FAQ form

### PR DESCRIPTION
**Pull request by Lobi29**
### **Solution :** 

**I have successfully added the Post request to the API from the FAQ form.**

### CODE REVIEW

**Comment by Grab-Bits** [comment]
Same for this file #62

**Comment by Lobi29** [comment]
sorry for this inconvenience,

I have made an another pull request #67 where all these issues successfully solve.
Please consider that pull request instead of this 

new pull request 👍🏻  #67

**Comment by kuvamdazeus** [comment]
Hey @Lobi29 

I have merged PR #67 
Should I close this one & PR #62 too?

**Comment by Lobi29** [comment]
yes this one also 👍🏻

**Pull request closed without merging**
