### PR TITLE
Overwriting removed on Podcast Page

### PR DESCRIPTION
**Pull request by Tisha6661**
## Related Issue

Closes: #[issue number]
#217 

## Description of Changes
- Changes made to remove overwriting on the podcast page from the video.
- Updated the Podcast.jsx and Podcast..module.css
- Subheading is changed according to the text in the video, to mix it with the surrounding.

## Checklist:

- [x] My code adheres to the established style guidelines of this project.
- [x] I have conducted a self-review of my code.
- [x] I have included comments in areas that may be difficult to understand.
- [x] I have made corresponding updates to the project documentation.
- [x] My changes have not introduced any new warnings.

## Screenshots

|      Original       |       Updated        |
| :-----------------: | :------------------: |
|Screenshot 2023-06-24 184157 | image |
|image | image|

### CODE REVIEW

**Comment by Grab-Bits** [comment]
Great work @Tisha6661 , just needed a quick change that explore button should be completely visible on the screen and also the button should scroll the user down 
Adding a ss for clarity - 
image

**Comment by Tisha6661** [comment]
@Grab-Bits The changes are done, here are the results-
image

**Comment by Bhushan8177** [comment]
Great job @Tisha6661 ,Merging this !!

**Comment by Bhushan8177** [comment]
Thank you for Contributing to GrabBit!!
Please ⭐ the repository and follow me on Github ...!

You can connect with me on Linkedin - 
https://www.linkedin.com/in/bhushan-kale/

**Pull request merged**
