### PR TITLE
Contact Us Form Different Look on Large Screens Correction

### PR DESCRIPTION
**Pull request by iamRabia-N**
## Related Issue
This PR contains the updated code for the consistent design of contact form on large screens. This PR is the result of the following issue:
Contact Us Form Different Look on Large Screens #194
Closes: #194

## Description of Changes
Correction of styling in contact form to make it appear same on large screens.

## Checklist:
- [x] My code adheres to the established style guidelines of this project.
- [x] I have conducted a self-review of my code.
- [x] I have included comments in areas that may be difficult to understand.
- [ ] I have made corresponding updates to the project documentation.
- [x] My changes have not introduced any new warnings.

## Screenshots

|      Original       |       Updated        |
| :-----------------: | :------------------: |
| grabbits (1)  | grabbit-2nd-pr (2) |

### CODE REVIEW

**Comment by Bhushan8177** [comment]
Great job @iamRabia-N , Merging this !!

**Comment by Bhushan8177** [comment]
Thank you for Contributing to GrabBit!!
Please ⭐ the repository and follow me on Github ...!

You can connect with me on Linkedin - 
https://www.linkedin.com/in/bhushan-kale/

**Comment by iamRabia-N** [comment]
@Bhushan8177 Kindly add labels and levels

**Comment by iamRabia-N** [comment]
@Grab-Bits kindly add level in this PR

**Pull request merged**
