### PR TITLE
feat: improve loader on opportunities page

### PR DESCRIPTION
**Pull request by harmeetsingh11**
## Related Issue

Closes: #154 

## Description of Changes
- Added a cool animation loader on opportunities page using Vanilla CSS.

## Files modified
- `client/src/components/Opportunities/Opportunities.jsx`
- `client/src/components/Opportunities/Opportunities.module.css`
- `client/src/components/common/Loader/Loader.jsx`
- `client/src/components/common/Loader/Loader.module.css`

### Before this PR
image

### After this PR
[Grab-Bits.webm](https://github.com/GrabBits/GrabBits_Website/assets/130365071/430b9508-5e7d-431e-922d-09f2a7e5e12f)

## Checklist:

- [x] My code adheres to the established style guidelines of this project.
- [x] I have conducted a self-review of my code.
- [ ] I have included comments in areas that may be difficult to understand.
- [ ] I have made corresponding updates to the project documentation.
- [x] My changes have not introduced any new warnings.

### CODE REVIEW

**Comment by Grab-Bits** [comment]
Hey @harmeetsingh11 , I guess the loader is being applied to both the whole website as well as the opportunities page !!
We want this loader only for the opportunities page, else great work I will merge it  after the changes are done 🙌

**Comment by harmeetsingh11** [comment]
@Grab-Bits please review the suggested changes. Here is the demo video:

[Grab-Bits.webm](https://github.com/GrabBits/GrabBits_Website/assets/130365071/f5d9d7ca-dd97-4850-b3fc-88a75e7e44da)

**Comment by Bhushan8177** [comment]
Great work @harmeetsingh11 , Merging this !!

**Comment by Bhushan8177** [comment]
Thank you for Contributing to GrabBit!!
Please ⭐ the repository and follow me on Github ...!

You can connect with me on Linkedin - 
https://www.linkedin.com/in/bhushan-kale/

**Pull request merged**
